"""Generate strict backend records from the published OpenAPI (no runtime YAML reads)."""

import hashlib
import json
import subprocess
import sys
from pathlib import Path
from typing import Any

import yaml  # type: ignore[import-untyped]

ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "backend/src/llm_model_explorer/architecture_analysis/records.py"


def generate() -> str:
    schemas = yaml.safe_load((ROOT / "docs/spec/api/openapi.yaml").read_text())["components"][
        "schemas"
    ]
    ordered: dict[str, Any] = {}

    def visit(name: str) -> None:
        if name in ordered:
            return

        def refs(value: Any) -> None:
            if isinstance(value, dict):
                if "$ref" in value:
                    visit(value["$ref"].rsplit("/", 1)[1])
                for item in value.values():
                    refs(item)
            elif isinstance(value, list):
                for item in value:
                    refs(item)

        refs(schemas[name])
        ordered[name] = schemas[name]

    visit("ArchitectureGraph")

    def annotation(s: dict[str, Any]) -> str:
        if "$ref" in s:
            return str(s["$ref"].rsplit("/", 1)[1])
        if "const" in s or "enum" in s:
            return "Literal[" + ", ".join(repr(v) for v in s.get("enum", [s.get("const")])) + "]"
        if "oneOf" in s:
            union = " | ".join(annotation(x) for x in s["oneOf"])
            if "discriminator" in s:
                discriminator = s["discriminator"]["propertyName"]
                return f"Annotated[{union}, Field(discriminator={discriminator!r})]"
            return union
        if isinstance(s.get("type"), list):
            return " | ".join(annotation({**s, "type": kind}) for kind in s["type"])
        kind = s["type"]
        base = {
            "string": "str",
            "integer": "int",
            "number": "float",
            "boolean": "bool",
            "null": "None",
            "array": "list",
        }.get(kind)
        if base is None:
            raise ValueError(f"Unsupported schema type: {kind}")
        if kind == "array":
            base = f"list[{annotation(s['items'])}]"
        constraints = []
        for source, target in [
            ("minLength", "min_length"),
            ("maxLength", "max_length"),
            ("minItems", "min_length"),
            ("maxItems", "max_length"),
            ("minimum", "ge"),
            ("maximum", "le"),
            ("pattern", "pattern"),
        ]:
            if source in s and (
                (source in ("minLength", "maxLength", "pattern") and kind == "string")
                or (source in ("minItems", "maxItems") and kind == "array")
                or (source in ("minimum", "maximum") and kind in ("integer", "number"))
            ):
                constraints.append(f"{target}={s[source]!r}")
        if constraints:
            return f"Annotated[{base}, Field({', '.join(constraints)})]"
        return base

    digest = hashlib.sha256(json.dumps(ordered, sort_keys=True).encode()).hexdigest()
    lines = [
        "# Generated by scripts/generate_architecture_records.py; do not edit.",
        "from typing import Annotated, Any, Literal",
        "",
        "from pydantic import BaseModel, ConfigDict, Field, model_validator",
        "",
        f"SCHEMA_REVISION = {digest!r}",
        "",
        "class Record(BaseModel):",
        '    model_config = ConfigDict(extra="forbid", frozen=True, strict=True,',
        '                              allow_inf_nan=False, regex_engine="python-re",',
        '                              revalidate_instances="never")',
        "",
        '    @model_validator(mode="before")',
        "    @classmethod",
        "    def absent_optional_fields(cls, value: Any) -> Any:",
        "        if isinstance(value, dict):",
        "            for name, field in cls.model_fields.items():",
        "                if not field.is_required() and name in value and value[name] is None:",
        '                    raise ValueError("Optional fields must be absent, not null")',
        "        return value",
        "",
        "    def document(self) -> dict[str, Any]:",
        '        return self.model_dump(mode="json", exclude_unset=True)',
        "",
    ]
    for name, schema in ordered.items():
        if schema.get("type") != "object":
            lines.extend([f"{name} = {annotation(schema)}", ""])
            continue
        lines.append(f"class {name}(Record):")
        required = schema.get("required", [])
        for prop, definition in schema["properties"].items():
            optional = " | None = None" if prop not in required else ""
            lines.append(f"    {prop}: {annotation(definition)}{optional}")
        lines.append("")
    return subprocess.run(
        [sys.executable, "-m", "ruff", "format", "--stdin-filename", str(OUTPUT)],
        input="\n".join(lines),
        capture_output=True,
        text=True,
        check=True,
    ).stdout


if __name__ == "__main__":
    output = generate()
    if "--check" in sys.argv:
        if OUTPUT.read_text() != output:
            raise SystemExit("Architecture records drifted; regenerate from OpenAPI.")
    else:
        OUTPUT.write_text(output)
