# Generated by scripts/generate_architecture_records.py; do not edit.
from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator

SCHEMA_REVISION = "390680271011b2c73dc8d8e945d548c5638cce2aaadfeda0030dfd67f475c7f1"


class Record(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
        strict=True,
        allow_inf_nan=False,
        regex_engine="python-re",
        revalidate_instances="never",
    )

    @model_validator(mode="before")
    @classmethod
    def absent_optional_fields(cls, value: Any) -> Any:
        if isinstance(value, dict):
            for name, field in cls.model_fields.items():
                if not field.is_required() and name in value and value[name] is None:
                    raise ValueError("Optional fields must be absent, not null")
        return value

    def document(self) -> dict[str, Any]:
        return self.model_dump(mode="json", exclude_unset=True)


ModelRevision = Annotated[str, Field(min_length=1, max_length=128, pattern="^[A-Za-z0-9_-]+$")]


class Session(Record):
    id: str
    model_id: Annotated[str, Field(min_length=1)]
    model_revision: ModelRevision


ObservedModelId = Annotated[str, Field(min_length=1)]


class ModelStatePresent(Record):
    epoch: str
    sequence: Annotated[int, Field(ge=0, le=9007199254740991)]
    model_id: ObservedModelId
    status: Literal["present"]
    model_revision: ModelRevision


class ModelStateUnavailable(Record):
    epoch: str
    sequence: Annotated[int, Field(ge=0, le=9007199254740991)]
    model_id: ObservedModelId
    status: Literal["unavailable"]
    model_revision: None


ModelState = Annotated[ModelStatePresent | ModelStateUnavailable, Field(discriminator="status")]


class ModelObservationError(Record):
    epoch: str
    sequence: Annotated[int, Field(ge=0, le=9007199254740991)]
    model_id: ObservedModelId
    code: Literal["observation_failed"]
