# Generated by scripts/generate_architecture_records.py; do not edit.
from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator

SCHEMA_REVISION = "845f3bc82e18dd37a23a044b9dc4b3ab356b406558816e63f3a988e471de4d38"


class Record(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
        strict=True,
        allow_inf_nan=False,
        regex_engine="python-re",
        revalidate_instances="never",
    )

    @model_validator(mode="before")
    @classmethod
    def absent_optional_fields(cls, value: Any) -> Any:
        if isinstance(value, dict):
            for name, field in cls.model_fields.items():
                if not field.is_required() and name in value and value[name] is None:
                    raise ValueError("Optional fields must be absent, not null")
        return value

    def document(self) -> dict[str, Any]:
        return self.model_dump(mode="json", exclude_unset=True)


ArchitectureId = Annotated[
    str, Field(min_length=1, max_length=256, pattern="^(?!\\.{1,2}$)[A-Za-z0-9._~-]+$")
]

ArchitectureName = Annotated[str, Field(min_length=1, max_length=1024)]

ArchitectureText = Annotated[str, Field(min_length=1, max_length=16384)]


class ArchitectureSymbol(Record):
    name: ArchitectureName
    meaning: ArchitectureText


SafeInteger = Annotated[int, Field(ge=0, le=9007199254740991)]


class ArchitectureConstantDimension(Record):
    kind: Literal["constant"]
    value: SafeInteger


class ArchitectureSymbolDimension(Record):
    kind: Literal["symbol"]
    name: ArchitectureName


class ArchitectureExpressionDimension(Record):
    kind: Literal["expression"]
    text: ArchitectureText
    symbols: Annotated[list[ArchitectureName], Field(max_length=33554432)]


class ArchitectureUnknownDimension(Record):
    kind: Literal["unknown"]
    reason: ArchitectureText


ArchitectureDimension = Annotated[
    ArchitectureConstantDimension
    | ArchitectureSymbolDimension
    | ArchitectureExpressionDimension
    | ArchitectureUnknownDimension,
    Field(discriminator="kind"),
]

ArchitectureShape = Annotated[list[ArchitectureDimension], Field(max_length=33554432)] | None


class ArchitecturePort(Record):
    id: ArchitectureId
    direction: Literal["input", "output"]
    label: ArchitectureName
    shape: ArchitectureShape


class ArchitectureModuleReference(Record):
    kind: Literal["module"]
    name: ArchitectureName


class ArchitectureParameterReference(Record):
    kind: Literal["parameter"]
    parameter_id: ArchitectureId


class ArchitectureTokenizerReference(Record):
    kind: Literal["tokenizer"]


ArchitectureReference = Annotated[
    ArchitectureModuleReference | ArchitectureParameterReference | ArchitectureTokenizerReference,
    Field(discriminator="kind"),
]


class ArchitectureProvenance(Record):
    kind: Literal["configuration", "storage", "description"]
    source: ArchitectureName
    revision: ArchitectureName | None = None
    rule: ArchitectureText | None = None


class ArchitectureAttribute(Record):
    name: ArchitectureName
    value: (
        Annotated[str, Field(max_length=16384)]
        | float
        | bool
        | None
        | Annotated[
            list[Annotated[str, Field(max_length=16384)] | float | bool | None],
            Field(max_length=33554432),
        ]
    )
    provenance: Annotated[list[ArchitectureProvenance], Field(max_length=33554432)]


class ArchitectureLeafNode(Record):
    id: ArchitectureId
    kind: Literal["operation", "input", "output", "context", "state"]
    label: ArchitectureName
    ports: Annotated[list[ArchitecturePort], Field(max_length=33554432)]
    parameter_ids: Annotated[list[ArchitectureId], Field(max_length=33554432)]
    references: Annotated[list[ArchitectureReference], Field(max_length=33554432)]
    attributes: Annotated[list[ArchitectureAttribute], Field(max_length=33554432)]
    provenance: Annotated[list[ArchitectureProvenance], Field(max_length=33554432)]
    parent_id: ArchitectureId | None = None
    operation: ArchitectureName | None = None
    description: ArchitectureText | None = None
    formula: ArchitectureText | None = None


class ArchitectureGroupNode(Record):
    id: ArchitectureId
    kind: Literal["group"]
    label: ArchitectureName
    ports: Annotated[list[ArchitecturePort], Field(max_length=33554432)]
    parameter_ids: Annotated[list[ArchitectureId], Field(max_length=33554432)]
    references: Annotated[list[ArchitectureReference], Field(max_length=33554432)]
    attributes: Annotated[list[ArchitectureAttribute], Field(max_length=33554432)]
    provenance: Annotated[list[ArchitectureProvenance], Field(max_length=33554432)]
    parent_id: ArchitectureId | None = None
    operation: ArchitectureName | None = None
    description: ArchitectureText | None = None
    formula: ArchitectureText | None = None
    children: Annotated[list[ArchitectureId], Field(max_length=33554432)]


ArchitectureNode = Annotated[
    ArchitectureLeafNode | ArchitectureGroupNode, Field(discriminator="kind")
]


class ArchitectureEndpoint(Record):
    node_id: ArchitectureId
    port_id: ArchitectureId


class ArchitectureEdge(Record):
    id: ArchitectureId
    source: ArchitectureEndpoint
    target: ArchitectureEndpoint
    kind: Literal["data", "state", "context"]
    provenance: Annotated[list[ArchitectureProvenance], Field(max_length=33554432)]
    label: ArchitectureName | None = None


class ArchitectureRepetitionInstance(Record):
    node_id: ArchitectureId
    index: SafeInteger
    variant: ArchitectureId


class ArchitectureRepetition(Record):
    id: ArchitectureId
    parent_id: ArchitectureId
    label: ArchitectureName
    instances: Annotated[list[ArchitectureRepetitionInstance], Field(max_length=33554432)]


TensorShape = list[SafeInteger]


class ArchitectureStorage(Record):
    name: ArchitectureName
    dtype: ArchitectureName
    shape: TensorShape
    role: ArchitectureName | None = None


class ArchitectureAvailableInspection(Record):
    status: Literal["available"]
    tensor_id: ArchitectureId


class ArchitectureUnavailableInspection(Record):
    status: Literal["unavailable"]
    reason: Literal[
        "unsupported_representation", "unsupported_rank", "requires_view", "unresolved_binding"
    ]
    message: ArchitectureText


ArchitectureInspection = Annotated[
    ArchitectureAvailableInspection | ArchitectureUnavailableInspection,
    Field(discriminator="status"),
]


class ArchitectureDirectParameter(Record):
    id: ArchitectureId
    name: ArchitectureName
    logical_shape: ArchitectureShape
    binding: Literal["native", "quantized", "unresolved"]
    storage: Annotated[list[ArchitectureStorage], Field(max_length=33554432)]
    inspection: ArchitectureInspection
    provenance: Annotated[list[ArchitectureProvenance], Field(max_length=33554432)]


class ArchitectureAliasParameter(Record):
    id: ArchitectureId
    name: ArchitectureName
    logical_shape: ArchitectureShape
    binding: Literal["alias"]
    storage: Annotated[list[ArchitectureStorage], Field(max_length=33554432)]
    inspection: ArchitectureInspection
    provenance: Annotated[list[ArchitectureProvenance], Field(max_length=33554432)]
    alias_of: ArchitectureId


class ArchitectureRegion(Record):
    storage_name: ArchitectureName
    description: ArchitectureText


class ArchitectureFusedParameter(Record):
    id: ArchitectureId
    name: ArchitectureName
    logical_shape: ArchitectureShape
    binding: Literal["fused_region"]
    storage: Annotated[list[ArchitectureStorage], Field(max_length=33554432)]
    inspection: ArchitectureInspection
    provenance: Annotated[list[ArchitectureProvenance], Field(max_length=33554432)]
    region: ArchitectureRegion


ArchitectureParameter = Annotated[
    ArchitectureDirectParameter | ArchitectureAliasParameter | ArchitectureFusedParameter,
    Field(discriminator="binding"),
]


class ArchitectureDiagnostic(Record):
    code: ArchitectureName
    message: ArchitectureText
    node_id: ArchitectureId | None = None
    parameter_id: ArchitectureId | None = None


class ArchitectureTemplateNodeRole(Record):
    role: ArchitectureId
    node_id: ArchitectureId


class ArchitectureTemplatePortRole(Record):
    role: ArchitectureId
    node_id: ArchitectureId
    port_id: ArchitectureId


class ArchitectureTemplateEdgeRole(Record):
    role: ArchitectureId
    edge_id: ArchitectureId


class ArchitectureTemplateParameterRole(Record):
    role: ArchitectureId
    parameter_id: ArchitectureId


class ArchitectureTemplateInstance(Record):
    node_id: ArchitectureId
    nodes: Annotated[list[ArchitectureTemplateNodeRole], Field(max_length=33554432)]
    ports: Annotated[list[ArchitectureTemplatePortRole], Field(max_length=33554432)]
    edges: Annotated[list[ArchitectureTemplateEdgeRole], Field(max_length=33554432)]
    parameters: Annotated[list[ArchitectureTemplateParameterRole], Field(max_length=33554432)]


class ArchitectureTemplate(Record):
    id: ArchitectureId
    label: ArchitectureName
    component_role: Literal["attention", "mlp"]
    revision: ArchitectureName
    provenance: Annotated[list[ArchitectureProvenance], Field(min_length=1, max_length=33554432)]
    instances: Annotated[
        list[ArchitectureTemplateInstance], Field(min_length=2, max_length=33554432)
    ]


class ArchitectureGraph(Record):
    graph_id: ArchitectureId
    scope: Literal["language_model", "visual_encoder_predictor"]
    coverage: Literal["complete", "partial"]
    symbols: Annotated[list[ArchitectureSymbol], Field(max_length=33554432)]
    nodes: Annotated[list[ArchitectureNode], Field(min_length=1, max_length=33554432)]
    edges: Annotated[list[ArchitectureEdge], Field(max_length=33554432)]
    repetitions: Annotated[list[ArchitectureRepetition], Field(max_length=33554432)]
    parameters: Annotated[list[ArchitectureParameter], Field(max_length=33554432)]
    diagnostics: Annotated[list[ArchitectureDiagnostic], Field(max_length=33554432)]
    templates: Annotated[list[ArchitectureTemplate], Field(max_length=33554432)] | None = None
