import { readFile, writeFile } from 'node:fs/promises';
import openapiTS, { astToString } from 'openapi-typescript';
import { parse } from 'yaml';

const source = new URL('../../../docs/spec/api/openapi.yaml', import.meta.url);
const document = parse(await readFile(source, 'utf8'));
const responses = {};
for (const path of Object.values(document.paths)) {
  for (const operation of Object.values(path)) {
    if (!operation.operationId) continue;
    const response = Object.entries(operation.responses).find(([status]) => /^2/.test(status))?.[1];
    const schema = response?.content?.['application/json']?.schema;
    if (schema) responses[operation.operationId] = schema;
  }
}
const files = {
  'types.ts': '// Generated by npm run api:generate. Do not edit.\n' + astToString(await openapiTS(source, { defaultNonNullable: false })),
  'schemas.json': JSON.stringify({ components: { schemas: document.components.schemas }, $defs: responses }, null, 2) + '\n',
};
for (const [name, content] of Object.entries(files)) {
  const target = new URL(`../../src/api/generated/${name}`, import.meta.url);
  if (process.argv.includes('--check')) {
    if (await readFile(target, 'utf8').catch(() => '') !== content) throw new Error(`${name} is stale; run npm run api:generate`);
  } else await writeFile(target, content);
}
